title: The Uncertain Path of A Confused Individual
author: Felix Chen
email: Felixx.Chenn@gmail.com
description: Embark on a journey with me to find out what I can truly do and who I am.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
